### PR TITLE
Rocko branch pull request

### PR DESCRIPTION
**Pull request by watatuki**
Hi schnitzeltony.

I fixed a build error in meta-qt5-extra. Please merge if you do not mind.
I think this patch is also necessary for master.
I have confirmed not to conflict, but I have not tested these patches with master branch.

### CODE REVIEW

**Comment by schnitzeltony** [comment]
OK - I found some time to check/test:

All patches change file access rights from 644 -> 755 - please correct that.

* Patch 1 / https://github.com/schnitzeltony/meta-qt5-extra/pull/43/commits/73144612ba061e8af9f03a66dce2a62cdde9c925: The current location works perfectly fine - why change? BTW pointed to this I will try to update to 0.7.5 in master (which lives in github) soon
* Patch 2 / https://github.com/schnitzeltony/meta-qt5-extra/pull/43/commits/7b817321be2554f47c228df2d1cdfad13918c630:
    1. Please mention recipe in commit
    2. In my environment exiv2 builds fine. Please add more details in commit message of the error you get (log) and what environment you use (e.g musl/clang...)
* Patch 3 / https://github.com/schnitzeltony/meta-qt5-extra/pull/43/commits/17ea6a37048b8043a90484512195093ebc156401: Same here: Have tested the recipe without errors. What error do you get in which environment?

**Comment by watatuki** [comment]
Thank you for review.

I will recheck about your review comment.

>Patch 1 / 7314461: 
When I wrote this patch, there was a fetch error.   When the server may had been down at that time , so I will recheck it.

>Patch 2 / 7b81732:
>Patch 3 / 17ea6a3:
My environment is as follows:
Yocto2.4.2 (rocko)
arm32 (jetson tk1) with gcc 7.3 / glibc 
meta-qt5 (rocko branch)

Details of the build error will be added later.

**Comment by watatuki** [comment]
Patch 2
When building with the original recipe, I get this error in my environment.

| CMakeFiles/Makefile2:277: recipe for target 'src/CMakeFiles/exiv2.dir/all' failed
| make[1]: *** [src/CMakeFiles/exiv2.dir/all] Error 2
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_unlock'
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_init'
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_rdlock'
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_destroy'
| ../src/libexiv2.so.26.0.0: undefined reference to `pthread_rwlock_wrlock'

The same error appears in the build of all executable files.   This seems to be due to libpthread not linked.


Patch 3
When building with the original recipe, I get this error in my environment.

tmp/work/cortexa15hf-neon-fireduck-linux-gnueabi/ladspa-sdk/1.13-r0/temp/run.do_compile.7692: 105: export: --hash-style: bad variable name

This error seems to be due to this description of the recipe.
export LDLDFLAGS=`echo ${LDFLAGS} | sed s:-Wl,::g`

I changed to use CC instead of LD to fix this problem.

**Comment by watatuki** [comment]
Patch 1: As a result of rechecking, this patch became unnecessary.

I close this ticket to fix the patch.

**Pull request closed without merging**
