### PR TITLE
qtbase: drop patch for qt5.5

### PR DESCRIPTION
**Pull request by YannickKiekens**
0001-Add-a-function-for-QPA-plugins-to-explicitly-destroy.patch, does not apply on qt5.5

### CODE REVIEW

**Comment by schnitzeltony** [comment]
Thanks for the patch. I need to wait testing/applying a bit.

That's because I am still using qt 5.4 for with meta-fsl arm. meta-fsl arm
is very special for vivante egl visual ID hack. There was another hack
applied in qtbase mainline (!). Hope somebody stands up for meta-fsl-arm
soon as I don't have time to do so currently.

Andreas

**Comment by YannickKiekens** [comment]
Maybe it's better to copy the branch names from meta-qt.
branch fido stays on qt5.4
master goes to 5.5

I am working on qt5.5 on the raspberry pi 2 on my fork

**Comment by schnitzeltony** [comment]
On Wed, Sep 2, 2015 at 9:21 AM, Yannick Kiekens <notifications@github.com>
wrote:

> Maybe it's better to copy the branch names from meta-qt.
> branch fido stays on qt5.4
> master goes to 5.5
>
Yes agreed but but this takes a bit of time to test.

> I am working on qt5.5 on the raspberry pi 2 on my fork
>
Raspi2 is also one of my targets. Note that parts of this layer will not
work as long as we have no X11 and/or Wayland EGL support for RasPi(2).
Have no logs available but kdeclarative (and all depending on it) and
khelpcenter fail with sometimes misleading error messages (libepoxy
conflicts).

Andreas

**Comment by schnitzeltony** [comment]
On Wed, Sep 2, 2015 at 9:43 AM, Andreas Müller
<schnitzeltony@googlemail.com> wrote:
> On Wed, Sep 2, 2015 at 9:21 AM, Yannick Kiekens <notifications@github.com>
> wrote:
>>
>> Maybe it's better to copy the branch names from meta-qt.
>> branch fido stays on qt5.4
>> master goes to 5.5
>
> Yes agreed but but this takes a bit of time to test.
>>
>> I am working on qt5.5 on the raspberry pi 2 on my fork
>
> Raspi2 is also one of my targets. Note that parts of this layer will not
> work as long as we have no X11 and/or Wayland EGL support for RasPi(2). Have
> no logs available but kdeclarative (and all depending on it) and khelpcenter
> fail with sometimes misleading error messages (libepoxy conflicts).
>
> Andreas
>
May I add signed-off to your commits?

Andreas

**Comment by YannickKiekens** [comment]
Shure, no problem

**Comment by schnitzeltony** [comment]
* 1st patch landed in [1]
* 2nd had to be rebased - see [2]

[1] https://github.com/schnitzeltony/meta-qt5-extra/commit/45dba19684e3a88671063dd17f12f89dbe33ce1e
[2] https://github.com/schnitzeltony/meta-qt5-extra/commit/1c718f0c9c1d73a61a9474c37ba053dcb2655eea

**Pull request closed without merging**
