### PR TITLE
Liri recipes and fixes

### PR DESCRIPTION
**Pull request by plfiorini**

### CODE REVIEW

**Comment by plfiorini** [comment]
This summer we merged Hawaii, Papyros and the Liri Project applications into one bigger project that is now called Liri. Since we are about to officially announce it and make the first release it's time to update the recipes.

The recipes here automatically fetch sources from the develop branch that now requires Qt 5.8.

I'm building meta-qt5-extra along with Boot2Qt and Poky krogoth with this distro: https://github.com/lirios/meta-liri

**Comment by schnitzeltony** [comment]
Wow - all this was on my TODO [1] - will merge it soon after review/test

[1] https://github.com/schnitzeltony/meta-qt5-extra/issues/19

**Comment by schnitzeltony** [comment]
One thing I saw from a first glance: Please don't use AUTOREV

* It makes parsing impossible when network connection is missing
* From my experience in the past with hawai: Every source update I did was
more than just updating SRCREV
* If nobody else wants: I am willing to maintain liri source revisions

**Comment by plfiorini** [comment]
Guess I can use AUTOREV in meta-liri bbappend and keep fixed revisions in meta-qt5-extra.
Until Liri OS 0.10.0 is out I need AUTOREV for the develop branch because the branch is work in progress until it is ready for release, then it will be merged with master that according to the git flow workflow contains the latest stable version.

If you can maintain source revisions that would be great. It will also be easier once Liri OS 0.10.0 is released.

**Comment by plfiorini** [comment]
@schnitzeltony Force pushed a new version w/o AUTOREV

**Comment by schnitzeltony** [comment]
I have pushed your patches

* Move lxqt-l10n dependency to lxqt-world
* phonon: Update to 4.9.0
* kcrash: Depends on libxcb

and added a small fix for kcrash and other pending fixes/updates

With the transition of hawaii -> liri patches I'll wait until meta-qt5
master has Qt 5.8 (I have to create a morty branch then..)

**Comment by plfiorini** [comment]
Ok, patch rebased

**Comment by schnitzeltony** [comment]
My email seems to have vanished so I use web interface.
Now meta-qt5 master has Qt5.8. It needed some fix for meta-qt5-extra but now it seems to build fine - fixing patch goes out tomorrow.
First liri image is baking currently...

**Comment by plfiorini** [comment]
Wonderful!

**Comment by plfiorini** [comment]
@schnitzeltony did you update the hashes?

**Comment by schnitzeltony** [comment]
Will do that

**Comment by schnitzeltony** [comment]
Some notes:
* I have corrected some package because version(x.x.x+gitrev) > version(x.x.x)
* have still fallout - I think caused by Qt5.8. Am working on it...

**Comment by schnitzeltony** [comment]
To make liri-world green I had to remove -Werror for:

* liri-shell
* liri-workspace
* qtaccountsservice
* liri-terminal
* vibe
* fluid

You can either apply the patches or solve - I am out for today

**Comment by plfiorini** [comment]
I'll take a look, never got that error but I build on x86_64 (haven't got raspberypi2 past linker issues with bcm_host.so for liri-wayland yet).

**Pull request merged**
